/* This file is auto-generated by `bun run pricing:refresh`. Do not edit manually. */

import type { PricingCatalog } from "./pricing-types.js";

export const pricingCatalog = {
  fetchedAt: "2026-06-16T01:39:11.349Z",
  sources: {
    codex: {
      kind: "web",
      fetchedAt: "2026-06-16T01:39:11.349Z",
      reference: "https://developers.openai.com/api/docs/pricing",
    },
    claude: {
      kind: "web",
      fetchedAt: "2026-06-16T01:39:11.349Z",
      reference: "https://platform.claude.com/docs/en/about-claude/pricing",
    },
    kiro: {
      kind: "static",
      fetchedAt: "2026-06-16T01:39:11.349Z",
      reference: "local-static:kiro-credit-overage-v1",
    },
  },
  codex: {
    defaultModel: "gpt-5-codex",
    models: {
      "codex-mini-latest": {
        input: 1.5,
        cachedInput: 0.375,
        output: 6,
      },
      "gpt-5-codex": {
        input: 1.25,
        cachedInput: 0.125,
        output: 10,
      },
      "gpt-5.1-codex": {
        input: 1.25,
        cachedInput: 0.125,
        output: 10,
      },
      "gpt-5.1-codex-max": {
        input: 1.25,
        cachedInput: 0.125,
        output: 10,
      },
      "gpt-5.1-codex-mini": {
        input: 0.25,
        cachedInput: 0.025,
        output: 2,
      },
      "gpt-5.2-codex": {
        input: 1.75,
        cachedInput: 0.175,
        output: 14,
      },
      "gpt-5.3-codex": {
        input: 1.75,
        cachedInput: 0.175,
        output: 14,
      },
    },
  },
  claude: {
    defaultFamily: "sonnet",
    families: {
      haiku: {
        label: "Claude Haiku",
        sourceModel: "Claude Haiku 4.5",
        input: 1,
        cacheWrite5m: 1.25,
        cacheWrite1h: 2,
        cacheRead: 0.1,
        output: 5,
      },
      opus: {
        label: "Claude Opus",
        sourceModel: "Claude Opus 4.8",
        input: 5,
        cacheWrite5m: 6.25,
        cacheWrite1h: 10,
        cacheRead: 0.5,
        output: 25,
      },
      sonnet: {
        label: "Claude Sonnet",
        sourceModel: "Claude Sonnet 4.6",
        input: 3,
        cacheWrite5m: 3.75,
        cacheWrite1h: 6,
        cacheRead: 0.3,
        output: 15,
      },
    },
  },
  kiro: {
    creditOverageUsd: 0.04,
  },
} satisfies PricingCatalog;
